### PR TITLE
Code Review for Tor DFPK

### PR DESCRIPTION
**Pull request by bertokhoury**

### CODE REVIEW

**Review by ianblenke — COMMENTED** [review]
I can help get this deployed as a hidden service so we can iterate on it.

**Comment by MasonAsh** [comment]
That would be helpful. For the time being we have tested that the REST server works in the orbot app over a local server, and we have tested that it can successfully make a request to an onion URL, but we haven't been able to test the REST server itself on an onion URL.

As it is currently the server is a self contained process and can be run via `python server.py` in the tor_auth_server directory and runs over localhost:8080. This can be modified to run over a proper webserver such as apache or nginx if need be.

**Comment by ianblenke** [comment]
I'll try and package that up and deploy it to the cloud today.

**Comment by ianblenke** [comment]
Merging and taking it from here. Merry Christmas!

**Pull request merged**
